### ISSUE TITLE
If no pinning service is configured, display the IPFS hash for images

### ISSUE THREAD

**Issue by manboy-eth** [gnosis/tabula#50]
If a user has not configured a pinning service, we should display a warning something like: 
"_Here is the hash of the image you uploaded, since you have not configured a pinning service you need to pin this hash yourself in order for the image to load for other users._" and display the hash.

The easiest is probably a modal, @cedricwaxwing?

**Comment by cedricwaxwing** [comment]
Yeah a modal makes sense here. Is there some way we can validate when the hash is pinned? Ideally we just disabled publishing until this is done (if I'm understanding this correctly).

**Comment by asgeir-eth** [comment]
> Yeah a modal makes sense here. Is there some way we can validate when the hash is pinned? Ideally we just disabled publishing until this is done (if I'm understanding this correctly).

I don't think that's something we can easily or should validate since it's not a strict requirement. It's just that the images they upload might not be retrievable, however, all text content will be available. So I don't think we should disable publishing. It's more like "If you want to make sure that your readers can see the image you uploaded, then pin this hash manually".

**Comment by juliopavila** [comment]
handle #238
