### ISSUE TITLE
Make it possible for an account to update articles in a publication

### ISSUE THREAD

**Issue by asgeir-eth** [gnosis/tabula#9]
An account that has `article/update` permissions to a publication should be able to update (overwrite) properties of articles in that publication.

Can use the same form as when creating an article, just pre-populate it with the article to be updated.

- [x] Subgraph
- [x] App
- [x] Design

**Comment by cedricwaxwing** [comment]
Design: https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=192%3A2486

The user can update an existing post by clicking the edit icon on the Posts page. They'll be brought to view that is very similar to the existing "Create Post" view, however, it will have the data from the existing post, and the button will say "Update Post" instead of "Publish Post"
